import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/nav";
import AuthSessionProvider from "@/components/providers/session-provider";
import { Toaster } from "@/components/ui/sonner"
import StoreDebug from "@/components/debug/store-debug"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <Navigation />
        {/* <div className="hidden lg:block">
          <Toaster position="bottom-right" />
        </div>
        <div className="block lg:hidden">
          <Toaster position="top-right" />
        </div> */}
          {children}
          {process.env.NODE_ENV !== "production" && <StoreDebug />}
          </AuthSessionProvider>
      </body>
    </html>
  );
}
